mobile_base_controller: 
 type : "diff_drive_controller/DiffDriveController" 
 left_wheel : ['wheel_rear_left_joint', 'wheel_front_left_joint']
 right_wheel: ['wheel_rear_right_joint', 'wheel_front_right_joint']
 publish_rate: 20.0 # default: 50 
 pose_covariance_diagonal : [0.001, .001, 1000000., 1000000., 1000000., 1000.] 
 twist_covariance_diagonal: [0.001, .001, 1000000., 1000000., 1000000., 1000.] 
 # Wheel separation and diameter. These are both optional. 
 # diff_drive_controller will attempt to read either one or both from the 
 # URDF if not specified as a parameter 
 #  wheel_separation : 0.4 
 #  wheel_radius : 0.2 
 # Wheel separation and radius multipliers 
 #  wheel_separation_multiplier: 1.0 # default: 1.0  
 #  wheel_radius_multiplier : 1.0 # default: 1.0 
 # Velocity commands timeout [s], default 0.5 
 cmd_vel_timeout: 0.25 
 odom: true
 # Base frame_id 
 base_frame_id: base_link #default: base_link 
 # Velocity and acceleration limits 
 # Whenever a min_* is unspecified, default to -max_* 
 linear: 
  x: 
   has_velocity_limits : true 
   max_velocity : 1.0 # m/s 
   min_velocity : -0.5 # m/s 
   has_acceleration_limits: true 
   max_acceleration : 0.8 # m/s² 
   min_acceleration : -0.4 # m/s² 
   has_jerk_limits : true 
   max_jerk : 5.0 # m/s³ 
 angular: 
  z: 
   has_velocity_limits : true 
   max_velocity : 1.7 # rad/s 
   min_velocity : -1.7 # rad/s 
   has_acceleration_limits: true 
   max_acceleration : 1.5 # rad/s² 
   has_jerk_limits : true 
   max_jerk : 2.5 # rad/s³