gazebo_ros_control/pid_gains:
  wheel_rear_left_joint: {p: 1.0, i: 0.0, d: 1.0}
  wheel_rear_right_joint: {p: 1.0, i: 0.0, d: 1.0}
  wheel_front_left_joint: {p: 1.0, i: 0.0, d: 1.0}
  wheel_front_right_joint: {p: 1.0, i: 0.0, d: 1.0}
