arm_position_controller:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  panda_joint1_position_controller:
    type: position_controllers/JointPositionController
    joint: panda_joint1
    pid: {p: 1.0, i: 0.01, d: 0.05}

  panda_joint2_position_controller:
    type: position_controllers/JointPositionController
    joint: panda_joint2
    pid: {p: 1.0, i: 0.01, d: 0.05}

  panda_joint3_position_controller:
    type: position_controllers/JointPositionController
    joint: panda_joint3
    pid: {p: 1.0, i: 0.01, d: 0.05}
  
  panda_joint4_position_controller:
    type: position_controllers/JointPositionController
    joint: panda_joint4
    pid: {p: 1.0, i: 0.01, d: 0.05}
  
  panda_joint5_position_controller:
    type: position_controllers/JointPositionController
    joint: panda_joint5
    pid: {p: 1.0, i: 0.01, d: 0.05}

  panda_joint6_position_controller:
    type: position_controllers/JointPositionController
    joint: panda_joint6
    pid: {p: 1.0, i: 0.01, d: 0.05}

  panda_joint7_position_controller:
    type: position_controllers/JointPositionController
    joint: panda_joint7
    pid: {p: 1.0, i: 0.01, d: 0.05}

  # panda_joint7_position_controller:
  #   type: position_controllers/JointPositionController
  #   joint: panda_joint7
  #   pid: {p: 1.0, i: 0.01, d: 0.05}

  # panda_joint7_position_controller:
  #   type: position_controllers/JointPositionController
  #   joint: panda_joint7
  #   pid: {p: 1.0, i: 0.01, d: 0.05}























# joint_state_controller:
#   type: joint_state_controller/JointStateController
#   publish_rate: 20
 
# panda_joint1_position_controller:
#     type: position_controllers/JointPositionController
#     joint: panda_joint1
#     pid: {p: 100, i: 1.0, d: 0.0}


# # arm_position_controller:
# #   type: position_controllers/JointPositionController
# #   joints:
# #     - panda_joint1
# #     - panda_joint2
# #     - panda_joint3
# #     - panda_joint4
# #     - panda_joint5
# #     - panda_joint6
# #     - panda_joint7
# #   gains:
# #     panda_joint1:
# #       p: 100
# #       d: 1
# #       i: 1
# #       i_clamp: 1
# #     panda_joint2:
# #       p: 100
# #       d: 1
# #       i: 1
# #       i_clamp: 1
# #     panda_joint3:
# #       p: 100
# #       d: 1
# #       i: 1
# #       i_clamp: 1
# #     panda_joint4:
# #       p: 100
# #       d: 1
# #       i: 1
# #       i_clamp: 1
# #     panda_joint5:
# #       p: 100
# #       d: 1
# #       i: 1
# #       i_clamp: 1
# #     panda_joint6:
# #       p: 100
# #       d: 1
# #       i: 1
# #       i_clamp: 1
# #     panda_joint7:
# #       p: 100
# #       d: 1
# #       i: 1
# #       i_clamp: 1